<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Vichu-PC" name="week4.day1.MergeLeadFrameWork" tests="1" failures="0" timestamp="26 May 2018 17:15:07 GMT" time="85.671" errors="1">
  <testcase name="doMerge" time="85.671" classname="week4.day1.MergeLeadFrameWork">
    <error type="java.lang.RuntimeException">
      <![CDATA[java.lang.RuntimeException
at week2.day2.wdMethods.SeMethods.locateElement(SeMethods.java:114)
at week4.day1.MergeLeadFrameWork.doMerge(MergeLeadFrameWork.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- doMerge -->
</testsuite> <!-- week4.day1.MergeLeadFrameWork -->
